apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-b-deploy
  labels:
    app: service-b
spec:
  replicas: 3
  selector:
    matchLabels:
      app: service-b
  template:
    metadata:
      labels:
        app: service-b
    spec:
      containers:
      - name: nginx
        image: elazarmeijers/api-service-b:v4
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: SERVIS_C_HOST
          value: "svc-service-c"
        - name: SERVIS_C_PORT
          value: "8081"