apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-a-deploy
  labels:
    app: service-a
spec:
  replicas: 3
  selector:
    matchLabels:
      app: service-a
  template:
    metadata:
      labels:
        app: service-a
    spec:
      containers:
      - name: service-a-container
        image: elazarmeijers/api-service-a:v3
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: SERVIS_B_HOST
          value: "svc-service-b"
        - name: SERVIS_B_PORT
          value: "8080"

